config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  concern :oai_provider, BlacklightOaiProvider::Routes.new

  def uuid_constraint
    /\h{8}-\h{4}-\h{4}-\h{4}-\h{12}/
  end

  # Allows for both UUID and Local ID patterns
  def id_constraint
    /\h{8}-\h{4}-\h{4}-\h{4}-\h{12}|[A-Za-z0-9\-._~]*/
  end

  mount Blacklight::Engine => '/'
  root to: 'pages#homepage'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions' }

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :oai_provider

    concerns :searchable
    concerns :range_searchable
  end

  resource :acquired_materials, only: [:index], as: 'acquired_materials', path: '/acquired_materials',
                                controller: 'acquired_materials' do
    concerns :searchable
    concerns :range_searchable
  end

  resource :items, only: [:index], as: 'items', path: '/items', controller: 'items' do
    concerns :oai_provider

    concerns :searchable
    concerns :range_searchable
  end

  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  constraints(id: uuid_constraint) do
    get 'directory_tree/:id/:directory_id', to: 'directory_tree#show', as: 'directory_tree_node'
    defaults directory_id: 'root' do
      get 'directory_tree/:id', to: 'directory_tree#show', as: 'directory_tree_root'
    end
  end

  # Range Limit and Facet routes for DC
  get 'dc/range_limit/', to: 'digital_collections#range_limit'
  get 'dc/facet/:id', to: 'digital_collections#facet', as: 'digital_collections_facet'

  # DC Collection scoped routes
  constraints(id: id_constraint, collection: id_constraint) do
    get 'dc/:collection/range_limit/', to: 'digital_collections#range_limit'
    get 'dc/:collection/facet/:id', to: 'digital_collections#facet'
    get 'dc/:collection/featured', to: 'digital_collections#featured', as: 'featured_items'
    get 'dc/:collection/about', to: 'digital_collections#about', as: 'digital_collections_about'
    get 'dc/:collection/:id/media', to: 'digital_collections#media', constraints: { format: 'json' }
    get 'dc/:collection/:id', to: 'digital_collections#show'
    get 'dc/:collection', to: 'digital_collections#index', as: 'digital_collections'
  end

  # Special named route just for DC Portal to distinguish
  # from DC collection portals
  get 'dc' => 'digital_collections#index_portal', as: 'digital_collections_index_portal'

  # Must exist for facets to work from DC portal
  get 'dc' => 'digital_collections#index'

  # Avoids this error: "Unable to find track_digital_collections_path route helper."
  post 'digital_collections/:id/track', to: 'digital_collections#track', as: :track_digital_collections

  # Range Limit and Facet routes for DC
  get 'portal/range_limit/', to: 'portal#range_limit'
  get 'portal/facet/:id', to: 'portal#facet', as: 'portal_facet'

  # DC Collection scoped routes
  constraints(id: id_constraint, collection: id_constraint) do
    get 'portal/:collection/about', to: 'portal#about', as: 'portal_about'
    get 'portal/:collection/:id', to: 'portal#show'
    get 'portal/:collection', to: 'portal#index', as: 'portal'
  end

  # Special named route just for DC Portal to distinguish
  # from DC collection portals
  get 'portal' => 'portal#index_portal', as: 'portal_index_portal'

  # Must exist for facets to work from DC portal
  get 'portal' => 'portal#index'

  # Downloads
  get 'download/:id(/:ddr_file_type)' => 'downloads#show', :constraints => { id: uuid_constraint }, as: 'download'

  # Image Item Exports (PDF or ZIP)
  post 'export_zip/:id', to: 'export_images#export_zip', as: 'export_zip',
                         constraints: { id: uuid_constraint }
  post 'export_pdf/:id', to: 'export_images#export_pdf', as: 'export_pdf',
                         constraints: { id: uuid_constraint }

  post 'export_images/:id/verify_export_recaptcha', to: 'export_images#verify_export_recaptcha',
                                                    constraints: { id: uuid_constraint }

  get 'export_images/:id/verification', to: 'export_images#verification', as: 'verify_exportable',
                                        constraints: { id: uuid_constraint }

  # Streamable Media
  get 'stream/:id' => 'stream#show', as: 'stream', constraints: { id: id_constraint }

  # Captions
  get 'captions/:id/txt' => 'captions#text', as: 'captions_txt', constraints: { id: id_constraint }
  get 'captions/:id/pdf' => 'captions#pdf', as: 'captions_pdf', constraints: { id: id_constraint }
  get 'captions/:id' => 'captions#show', as: 'captions', constraints: { id: id_constraint }

  # Permanent IDs
  get 'id/*permanent_id' => 'permanent_ids#show'

  # Static Pages
  get '/homepage' => 'pages#homepage'

  # IIIF Image API
  get '/iiif/*identifier/info', to: 'iiif_images#info', defaults: { format: 'json' }
  get '/iiif/*identifier/:region/:size/:rotation/:quality', to: 'iiif_images#show'

  # IIIF Presentation API
  get '/iiif/*id/manifest', to: 'iiif_presentation#manifest', as: 'iiif_presentation', format: false
  get '/iiif/*id/manifest.json', to: redirect('/iiif/%{id}/manifest'), format: false

  # Default health check as of Rails 7.1
  get 'up', to: 'rails/health#show', as: :rails_health_check
  get 'healthz', to: 'rails/health#show', constraints: lambda { |_request|
    Rails.logger.warn "DEPRECATION WARNING: The custom 'healthz' route is deprecated. Please use the Rails default 'up' instead."
    true
  }
end

app/helpers/catalog_helper.rb
# frozen_string_literal: true

require 'open-uri'

# rubocop:disable Metrics/ModuleLength
module CatalogHelper
  include Blacklight::CatalogHelperBehavior

  # Predicate methods for object types
  def is_item?(document)
    document['common_model_name_ssi'] == 'Item'
  end

  def is_component?(document)
    document['common_model_name_ssi'] == 'Component'
  end

  def is_collection?(document)
    document['common_model_name_ssi'] == 'Collection'
  end

  def has_two_or_more_multires_images?(document)
    document.multires_image_file_paths.present? && document.multires_image_file_paths.length > 1
  end

  # Used in DC "about" pages to render inline img tags for items using local_id
  def item_image_embed(options = {})
    search_service = Blacklight::SearchService.new(config: blacklight_config,
                                                   user_params: { q: "local_id_ssi:#{options[:local_id]}",
                                                                  rows: 1 },
                                                   search_builder_class: ::ItemSearchBuilder)
    # search_service.search_results returns [@solr_response, @document_list]
    (_, doc_list) = search_service.search_results

    return if doc_list.empty?

    identifier = doc_list.first.multires_image_file_arks.first
    iiif_image_tag(identifier,
                   { size: options[:size], alt: doc_list.first.title_ssi, class: options[:class] })
  end

  # Used in DC "about" pages to render inline img tags for items using local_id
  def item_title_link(options = {})
    search_service = Blacklight::SearchService.new(config: blacklight_config,
                                                   user_params: { q: "local_id_ssi:#{options[:local_id]}",
                                                                  rows: 1 },
                                                   search_builder_class: ::ItemSearchBuilder)
    (response, doc_list) = search_service.search_results
    link_to_document(doc_list.first) unless response.empty?
  end

  # View helper: from EITHER collection show page or configured collection portal, browse items.
  def collection_browse_items_url(document, _options = {})
    if @portal
      search_action_url(search_state.add_facet_params('common_model_name_ssi', 'Item'))
    else
      source_params = { 'f[collection_title_ssi][]' => document['collection_title_ssi'],
                        'f[admin_set_title_ssi][]' => document['admin_set_title_ssi'] }
      search_action_url(
        controller.search_state_class.new(source_params, blacklight_config)
                  .add_facet_params('common_model_name_ssi', 'Item')
      )
    end
  end

  def item_browse_components_url(document, _options = {})
    search_action_url(search_state.add_facet_params('is_part_of_ssim', document.id)
                                  .merge({ show_components: 'true' }))
  end

  # Index / Show field view helper
  def file_info(options = {})
    document = options[:document]
    if cached_download_current_ability(document)
      render('download_link_and_icon', document:)
    elsif user_signed_in?
      render('download_not_authorized', document:)
    else
      render 'download_restricted', document:
    end
  end

  # View helper
  def render_download_link(args = {})
    return unless args[:document]

    label = icon('fas', 'download', 'Download')
    link_to label, download_path(args[:document]), class: args[:css_class], id: args[:css_id], data: args[:data]
  end

  # View helper
  def default_mime_type_label(mime_type)
    case mime_type
    when /^image/
      'Image'
    when /^video/
      'Video'
    when /^audio/
      'Audio'
    when %r{^application/(x-)?pdf}
      'PDF'
    when /^application/
      'Binary'
    when %r{^text/comma-separated-values}
      'CSV'
    else
      'File'
    end
  end

  def get_research_help(document)
    Timeout.timeout(2) do
      document.research_help
    end
  rescue StandardError => e
    Rails.logger.error { "#{e.message} #{e.backtrace.join("\n")}" }
    false
  end

  # View helper
  def research_help_title(research_help)
    link_to_if(research_help.url, research_help.name, research_help.url) if research_help.name.present?
  end

  def read_not_authorized_contact_name(research_help)
    return research_help.name if research_help && research_help.name.present?

    I18n.t('blacklight.branding.library_name')
  end

  def read_not_authorized_contact_url(research_help)
    if research_help && research_help.ask.present?
      "#{research_help.ask}?&referrer=#{request.original_url}"
    elsif research_help && research_help.email.present?
      "mailto:#{research_help.email}"
    else
      Ddr::Public.help_url
    end
  end

  # View helper
  def finding_aid_popover(finding_aid)
    popover = []
    if finding_aid.collection_title
      popover << ("<h4>#{finding_aid.collection_title}#{faid_date_span(finding_aid)}</h4>")
    end
    if finding_aid.collection_number || finding_aid.extent
      popover << ("<p class=\"small text-muted\">#{faid_collno_and_extent(finding_aid)}</p><hr/>")
    end
    popover << ("<p class=\"small\">#{finding_aid.abstract.truncate(250, separator: ' ')}</p>") if finding_aid.abstract
    if finding_aid.repository
      popover << ("<div class=\"small card bg-light\"><div class=\"card-body p-2\">View this item in person at:<br/>#{finding_aid.repository}</div></div>")
    end
    popover.join
  end

  # We need to (temporarily?) account for the fact that we have a mix of ASpace ID values
  # in DDR metadata: some have an aspace_* prefix and others do not. ArcLight
  # component URLs will always have the prefix, so it must be present in the link.
  def finding_aid_component_link(document)
    return unless document.aspace_id_ssi

    stored_id = document.aspace_id_ssi
    normalized_id = stored_id.start_with?('aspace_') ? stored_id : "aspace_#{stored_id}"
    [document.finding_aid.url, '_', normalized_id].join
  end

  # Find matching collections for the search results "Matching Collections" box. This
  # needs to use the SearchService's default search_builder_class b/c the scope varies by
  # controller (e.g., Acquired Materials vs. DC).
  def find_collection_results
    @find_collection_results ||=
      begin
        search_service = Blacklight::SearchService.new(config: blacklight_config,
                                                       search_state:,
                                                       **controller.search_service_context)

        # search_service.search_results returns [@solr_response, @document_list]
        (response, doc_list) = search_service.search_results do |builder|
          builder.append(:include_only_collections)
                 .except(:add_facetting_to_solr)
                 .except(:add_range_limit_params)
        end
        { docs: doc_list, count: response.dig(:response, :numFound)&.to_i }
      end
  end

  def show_collection_results?
    # We only want to show the matching collections box when a particular
    # combination of conditions is true:

    ### 1. There are matching collection results
    find_collection_results.fetch(:count).positive? &&

      # 2. The matching collection results aren't identical to the main results
      @response.documents.length != find_collection_results.fetch(:count) &&

      # 3. We are not in a single-collection portal context with a local_id like /dc/adaccess
      !@portal&.local_id &&

      # 4. We aren't currently faceted on Model (Collection, Item, Component)
      !params.dig(:f, :common_model_name_ssi) &&

      # 5. We are on the first page of results
      @response.first_page?
  end

  def get_blog_posts(blog_url)
    return if blog_url.blank?

    begin
      JSON.parse(
        URI.open(blog_url,
                 { read_timeout: 2 }).read
      )
    rescue Net::ReadTimeout, Errno::ECONNREFUSED, JSON::ParserError, OpenURI::HTTPError => e
      Rails.logger.error { "#{e.message} #{e.backtrace.join("\n")}" }
      fallback_link = link_to 'See All Blog Posts', 'https://blogs.library.duke.edu/bitstreams'
      "<p class='small'>#{fallback_link}</p>"
    end
  end

  def blog_post_thumb(post)
    # If a post has a selected "featured image", use that.
    # In the WP-JSON API, for some reason, thumbnail_images can either be
    # an empty array or a populated hash, so coerce to hash.
    post['thumbnail_images'] = post['thumbnail_images']&.to_h
    post.dig('thumbnail_images', 'thumbnail', 'url') || image_path('ddr/devillogo-150-square.jpg')
  end

  def link_to_admin_set(document, options = {})
    name = document['admin_set_title_ssi']
    url =  facet_search_url('admin_set_title_ssi', name)
    link_to name, url, class: options[:class], id: 'admin-set'
  end

  def research_guide(values = [])
    values.find { |value| is_research_guide? value } if values.present?
  end

  def document_dropdown_label(document)
    if document.structures.files.count == 1 &&
       document.structures.files.first[:doc].format.present?
      document.structures.files.first[:doc].format.join(' ')
    else
      I18n.t('ddr.public.document_dropdown')
    end
  end

  def link_to_search_inside_full_text(doc)
    url = "#{Ddr::Public.contentdm_url}/collection/" \
          "#{doc['contentdm_id_ssi']}"
    link_to(I18n.t('ddr.public.search_inside_dropdown.full_text_link'), url, class: 'dropdown-item')
  end

  def link_to_search_inside_pdf(doc)
    url = "#{Ddr::Public.contentdm_url}/api/collection/" \
          "#{doc['contentdm_id_ssi']}/page/0/inline/" \
          "#{doc['contentdm_id_ssi'].split('/id/').join('_')}_0"
    link_to(I18n.t('ddr.public.search_inside_dropdown.pdf_link'), url, class: 'dropdown-item')
  end

  private

  def facet_search_url(field, value)
    search_action_url(search_state.add_facet_params(field, value))
  end

  def derivative_file_extension(document)
    case document.display_format_ssi
    when 'audio'
      'mp3'
    when 'video'
      'mp4'
    end
  end

app/views/catalog/_display_interactive_transcript_menu.html.erb
<div class="dropdown">
  <a id="download-transcript-dropdown" class="btn btn-secondary dropdown-toggle" role="button" data-toggle="dropdown" href="#" aria-expanded="false" aria-label="Download transcript">
    <i class="fa-solid fa-download"></i>
  </a>
  <ul id="download-transcript-menu" class="dropdown-menu" aria-labelledby="download-transcript-dropdown">
    <li class="py-2 px-4 text-muted">Download transcript as:</li>

    <%# Single component show, or single-component item show %>
    <% if @document.captions_urls.length == 1 %>
    <li>
      <a download="" class="dropdown-item" href="<%= File.join(@document.captions_urls.first, 'txt') %>">
        <img alt="text icon" src="<%= asset_path 'ddr-icons/txt.png' %>" width="20" height="20">
        Text
      </a>
    </li>
    <li>
      <a download="" class="dropdown-item" href="<%= File.join(@document.captions_urls.first, 'pdf') %>">
        <img alt="pdf icon" src="<%= asset_path 'ddr-icons/pdf.png' %>" width="20" height="20">
        PDF
      </a>
    </li>
    <li>
      <a download="" class="dropdown-item" href="<%= @document.captions_urls.first %>">
        <img alt="code icon" src="<%= asset_path 'ddr-icons/code.png' %>" width="20" height="20">
        WebVTT <small class="text-muted">(includes timecodes)</small>
      </a>
    </li>
    <% end %>

    <%# Multi-component item show w/captions, render a different menu %>
    <% if @document.captions_urls.length > 1 %>
      <li class="dropdown-submenu">
        <a href="#" class="dropdown-item"><img alt="code icon" src="<%= asset_path 'ddr-icons/txt.png' %>" width="20" height="20"> Text</a>
        <ul class="dropdown-menu">
          <% @document.captions_urls.each_with_index do |captions_url, index| %>
            <li>
              <a class="dropdown-item" download="" href="<%= File.join(captions_url, 'txt') %>">
                Part <%= index + 1 %>
              </a>
            </li>
          <% end %>
        </ul>
      </li>

      <li class="dropdown-submenu">
        <a href="#" class="dropdown-item"><img alt="code icon" src="<%= asset_path 'ddr-icons/pdf.png' %>" width="20" height="20"> PDF</a>
        <ul class="dropdown-menu">
          <% @document.captions_urls.each_with_index do |captions_url, index| %>
            <li>
              <a class="dropdown-item" download="" href="<%= File.join(captions_url, 'pdf') %>">
                Part <%= index + 1 %>
              </a>
            </li>
          <% end %>
        </ul>
      </li>

      <li class="dropdown-submenu">
        <a href="#" class="dropdown-item"><img alt="code icon" src="<%= asset_path 'ddr-icons/code.png' %>" width="20" height="20"> WebVTT <small class="text-muted">(includes timecodes)</small></a>
        <ul class="dropdown-menu">
          <% @document.captions_urls.each_with_index do |captions_url, index| %>
            <li>
              <a class="dropdown-item" download="" href="<%= captions_url %>">
                Part <%= index + 1 %>
              </a>
            </li>
          <% end %>
        </ul>
      </li>

    <% end %>

  </ul>
</div>

app/views/catalog/_download_not_authorized.html.erb
<%= link_to icon('fas', 'lock', 'Not Authorized to Download'), '#', class: 'btn btn-sm btn-danger disabled' %>
<%= render 'component_type_and_size', document: document %>

app/views/catalog/_download_request.html.erb
<div id="download-request">
  <%= link_to t('ddr.public.request_download'),
              Ddr::Public.download_request_form,
              target: '_blank',
              id: 'bulk-download-link', rel: 'noopener' %>
</div>

app/views/catalog/_item_options_imagecount.html.erb
<% if imagecount > 1 %>
  <li class="nav-item">
    <a class="btn btn-link nav-link" href="#" id="imagecount-indicator">
      <%= icon(*@document.display_format_icon) %> <%= imagecount %> images
    </a>
  </li>
<% end %>

app/views/catalog/_javascript_tools_av.html.erb
<%# Pull in compiled AV-specific JS from javascripts/av/index.js %>
<%# See https://robots.thoughtbot.com/slicing-up-rails-application-js-for-faster-load-times %>
<% content_for(:head) do %>
  <%= javascript_include_tag 'av/index.js' %>
<% end %>

app/views/catalog/_related_items_default.html.erb
<% related_header = 'Related Collections' if document.common_model_name_ssi == 'Collection' %>

<div id="related-items">
  <% document.related_items.each do |related_item| %>
    <% if related_item.related_documents.present? %>
      <% if related_item.related_documents_count > 3 %>
        <h2 class="feature-head">
          <%= link_to("#{related_header ||= related_item.name.pluralize} (#{related_item.related_documents_count})", search_action_path(related_item.solr_query)) %>
        </h2>
      <% else %>
        <h2 class="feature-head">
          <%= related_header ||= related_item.name.pluralize(related_item.related_documents_count) %>
        </h2>
      <% end %>
      <%= render_document_index_with_view('gallery', related_item.related_documents[0..2]) %>
      <% if related_item.related_documents_count > 3 %>
        <%= link_to("See all #{related_item.related_documents_count} #{related_header ||= related_item.name.pluralize}", search_action_path(related_item.solr_query)) %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/catalog/_show_blog_post_feature.html.erb
<div class="media blog-post-feature mb-3">
  <div class="mr-3">
    <a href="<%= post['url'] %>" aria-label="Read the article: <%= post['title'] %>">
      <img class="media-object" src="<%= blog_post_thumb(post) %>" alt="">
    </a>
  </div>
  <div class="media-body">
    <h3><%= link_to(post['title'].html_safe, post['url']) %></h3>
    <p class="small text-muted">
      by <%= link_to(post['author']['name'], "https://blogs.library.duke.edu/bitstreams/author/#{post['author']['slug']}/", class: 'underlined-link') %> <span class="post-time-ago"><%= distance_of_time_in_words(DateTime.parse(post['date']), Time.zone.now) %> ago</span>
    </p>
    <div><%= post['excerpt'].html_safe %></div>

  </div>
</div>

app/views/catalog/_show_blog_posts.html.erb
<% cache("blog_posts_#{params[:collection]}", expires_in: 1.day) do %>
  <% @blog_posts = get_blog_posts(@portal.blog_posts_url) %>

  <% if @blog_posts && @blog_posts['posts'] %>

    <hr>

    <div id="blog-posts" class="mb-3">
      <h2 class="feature-head"><a href="https://blogs.library.duke.edu/bitstreams/">From Our Blog</a></h2>

      <% if @blog_posts['posts'].length > 2 %>

        <%= render 'show_blog_post_feature', post: @blog_posts['posts'].first %>

        <div class="row blog-secondary">
          <% @blog_posts['posts'].drop(1)[0..1].each do |post| %>
            <%= render 'show_blog_post_secondary', post: post %>
          <% end %>
        </div>

        <% if @blog_posts['posts'].length > 3 %>
          <% if @blog_posts['tag'] %>
            <div><%= link_to 'More Posts About This Collection', "https://blogs.library.duke.edu/bitstreams/tag/#{@blog_posts['tag']['slug']}/", { class: 'small text-muted' } %></div>
          <% else %>
            <div><%= link_to 'More Posts', 'https://blogs.library.duke.edu/bitstreams/', { class: 'small text-muted' } %></div>
          <% end %>
        <% end %>

      <% else %>
        <% @blog_posts['posts'].each do |post| %>
          <%= render 'show_blog_post_feature', post: post %>
        <% end %>
      <% end %>

    </div>

  <% end %>
<% end %>

app/views/catalog/_show_collection_sponsor.html.erb
<%# No collection sponsor Adopt-a-Collection box beyond digital collections %>
<%# See /app/views/digital_collections/_show_collection_sponsor.html.erb    %>

app/views/catalog/_show_finding_aid_full.html.erb
<% if document.has?('ead_id_ssi') %>
  <% finding_aid = document.finding_aid %>
  <% if finding_aid.data? %>
    <div class="card bg-light mb-3" id="source-collection">
      <div class="card-body">
        <h2 class="feature-head"><%= image_tag('ddr/archival-box.png', alt: '', class: 'collection-guide-icon') %>Source Collection</h2>

        <p class="small">This digital collection comprises selected materials from the following archival collection at <%= finding_aid.repository %>:</p>

        <h3 class="h4">
          <%= link_to finding_aid.collection_title, finding_aid.url %>
          <% if finding_aid.collection_date_span.present? %>
            <span class="small"> <%= finding_aid.collection_date_span %></span>
          <% end %>
        </h3>

        <p class="text-muted">
          <% if finding_aid.collection_number.present? %>
            Collection #<%= finding_aid.collection_number %> |
          <% end %>
          <% if finding_aid.extent.present? %>
            <%= finding_aid.extent %>
          <% end %>
        </p>

        <% if finding_aid.abstract.present? %>
          <p><span class="text-muted text-uppercase small strong">ABSTRACT</span><br><%= finding_aid.abstract %></p>
        <% end %>

          <p><%= link_to raw('Collection Guide &raquo;'), finding_aid.url %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/catalog/_show_finding_aid_links.html.erb
<% if document.ead_id_ssi.present? %>
  <div id="finding-aid" class="finding_aid">
    <%= source_collection({ document: document, placement: 'left', title: 'Source Collection' }) %>

    <% if document.aspace_id_ssi.present? %>
      <br/>
      <%= link_to 'View in Collection Guide',
                finding_aid_component_link(document),
                class: '',
                id: 'faid-deep-link' %>
    <% end %>
  </div>
<% end %>

app/views/catalog/_show_image_item.html.erb
<%= render 'display_image', document: document %>

app/views/catalog/_show_portal_context.html.erb
<div id="portal-context" class="mb-4">
  <h4><%= link_to t("ddr.public.portal.#{params[:collection] || controller_name}.title", default: 'Home'), url_for(action: 'index') %></h4>
  <p class="small"><%= t("ddr.public.portal.#{params[:collection] || controller_name}.about", default: '') %></p>
</div>

app/views/catalog/_timecode_links.html.erb
<script>

  function seconds(s) {
    var timecode = s.split('\) ').pop();
    var a = timecode.split(':');
    var sec = Number(a[a.length-1]) + Number(a[a.length-2]) * 60;
    if(a.length > 2) { sec+= Number(a[a.length-3]) * 3600; }
    return sec;
  };

  function getpart(s) {
    var part = s.split('\) ').shift().split('\(Part ').pop();
    if (!isNaN(part)) {
      return part
    } else {
      return '1'
    }
  }

  function timecodelink(match) {
    return "<a href='#' class='jump-av' data-jump-track='"+getpart(match)+"' data-jump-sec='"+seconds(match)+"'>"+match+"</a>";
  }

  function partlink(match) {
    return "<strong>"+match+"</strong>";
  }

  $(document).ready(function(){
    $('#item-info dd.blacklight-description_tsim').each(function() {
      var raw_text = $(this).html();

      <%# Some regex from https://stackoverflow.com/a/8318367 %>
      <%# Matches simple timecodes (w/optional leading zeroes) and %>
      <%# timecodes pertaining to a specific part (component) %>

      <%# EXAMPLES: %>
      <%# --------- %>
      <%# 0:45, 12:34, 00:01:34, 1:31:42 %>
      <%# (Part 1) 0:32, (Part 1) 1:23:45, (Part 2) 4:37 %>

      var timepart_regex = new RegExp(/(?:(\(Part\s[0-9][0-9]?\)\s)?(?:(?:([01]?\d|2[0-3]):)?([0-5]?\d):)([0-5]?\d))/g);
      var new_text = raw_text.replace(timepart_regex, timecodelink);

      $(this).html(new_text);
    });

    $(document).on('click', 'a.jump-av', function(e) {
      e.preventDefault();
      seconds = $(this).data('jump-sec');
      cue_track = $(this).data('jump-track');
      jwplayer().stop;
      jwplayer().playlistItem(cue_track - 1);
      jwplayer().seek(seconds);

      $('html,body').animate({
          scrollTop: $('#jwplayer-element').offset().top
      }, 750);
    });

  });
</script>